export const WSCONNECT = "wsconnect"
export const WSCONNECTED = "wsconnected"
export const WSCONNECTING = "wsconnecting"
export const WSFAILED = "wsfailed"
export const UPDATE_WSCONNECTIONSTATE = "update_wsconnectionstate"
export const WS_SEND_MESSAGE = "ws_send_message"

// export const UPDATE_WRTC_CONNECTION_STATE = "update_wrtc_connection_state"
export const WRTC_UPDATE_CONNECTION_STATE = "wrtc_update_connection_state"
export const WRTC_ANSWER = "wrtc_answer"
export const WRTC_CONNECTING = "wrtc_connecting"
export const WRTC_DISCONNECTED = "wrtc_disconnected"
export const WRTC_CONNECTED = "wrtc_connected"
export const WRTC_CONNECT = "wrtc_connect"
export const WRTC_OFFER = "wrtc_offer"
export const WRTC_ICE_CANDIDATE = "wrtc_ice_candidate"
export const WRTC_RENEGOTIATION = "wrtc_renegotiation"
export const WRTC_DISCONNECT = "wrtc_disconnect"
export const WRTC_ADD_TRACK = "wrtc_add_track"

